// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-core-data";

test("obix-binding-data: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["dataApply"], owner0["dataApply"], "dataApply");
  assert.equal(shim0["dataRender"], owner0["dataRender"], "dataRender");
  assert.equal(shim0["dataValidate"], owner0["dataValidate"], "dataValidate");
  assert.equal(shim0["toData"], owner0["toData"], "toData");
  assert.deepEqual(Object.keys(shim0).sort(), ["dataApply","dataRender","dataValidate","toData"]);
});
