// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { dataApply, dataRender, dataValidate, toData } from "obix-core-data";
